# Generated by Django 4.0.4 on 2022-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactus_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(choices=[('*', 'Not statisfied!'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], default='3', max_length=5),
        ),
    ]
