# Generated by Django 4.0.4 on 2022-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_restaurant_created_restaurant_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='make_public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
