# Generated by Django 4.0.4 on 2022-05-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_created_comment_date_added_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentBox',
        ),
    ]
