# Generated by Django 4.0.4 on 2022-05-26 08:39

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_comment_commentbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='pic',
            field=models.ImageField(upload_to='diaries_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], default='3', max_length=5),
        ),
    ]
