# Generated by Django 4.0.4 on 2022-05-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='pic',
            new_name='diary_image',
        ),
    ]
