# Generated by Django 4.0.4 on 2022-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_pic_diary_diary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_image',
            field=models.ImageField(blank=True, default='add.png', upload_to='diaries_pic'),
        ),
    ]
