# Generated by Django 4.0.4 on 2022-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_image',
            field=models.ImageField(blank=True, default='avatar.svg', upload_to='diary_pic'),
        ),
    ]
